### ISSUE TITLE
Game system improvement

### ISSUE THREAD

**Issue by ZMinghuiZ** [AY2324S2-CS2113-T11-4/tp#50]
- [x] Stock game development #47 
- [x] Company management system #53 
- [x] Random event #51 
- [x] Complete game logic design
- [x] UI improvement #49
